//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBaiXe.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Building
    {
        public int ID { get; set; }
        public Nullable<int> SumAvail { get; set; }
        public string FP7Status { get; set; }
        public Nullable<int> FP7Count { get; set; }
    
        public virtual BuildingInfo BuildingInfo { get; set; }
    }
}
