//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBaiXe.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fee
    {
        public int ID { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<int> SessionID { get; set; }
        public Nullable<float> Price { get; set; }
    
        public virtual FeeType FeeType { get; set; }
        public virtual FeeSession FeeSession { get; set; }
    }
}
